### ISSUE TITLE
question about reduction

### ISSUE THREAD

**Issue by jinz2014** [neozhang307/SyncMicrobenchmark#1]
Hi

"We use the reduction operator (summing the elements of an array) as a case study." Will you add the reduction kernels/operators described in the paper to the repo ?  Thanks.

**Comment by neozhang307** [comment]
The original repo is at https://github.com/neozhang307/Reduction. I also add the two reduction implementations (single GPU and multi-GPU) in this repo. 

I think the original code could run in P100 and V100, but currently, I don't have access to those platforms, so I could not check. I only update the configurations so that it can run in A100, which I can access right now.

Remember that the Reduction repo is only used as a case study to understand the performance of cooperative group APIs at the time. And currently, the multigrid related APIs are marked as deprecated. 

If you are comparing with SoTAs in a single GPU, CUB and thrust might still be a very good choice, as they will automatically adjust to any Nvidia Platforms. 

If you have further questions please don't hesitate to ask.
